eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
